server {
    client_max_body_size 100M;
    server_name pheme-dev.rh1.tech;
    access_log /var/log/nginx/pheme-dev.rh1.tech_access.log;
    error_log /var/log/nginx/pheme-dev.rh1.tech_error.log;

    location / {
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_pass http://127.0.0.1:8195;
    }

    listen 443 ssl;
    include /etc/nginx/snippets/rh1-tech-ssl.conf;
}
server {
    if ($host = pheme-dev.rh1.tech) {
        return 301 https://$host$request_uri;
    }
    server_name pheme-dev.rh1.tech;
    listen 80;
    return 404;
}
