// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `applied`, `bytes`, `mutate`, `read`

/// Mints a fresh identity for one DEVICE of one user and installs it as the live client.
///
/// All three are required. The domain qualifies the member so a person on one host is distinct
/// from a same-named person on another (the credential is `mimi://<domain>/d/<user>/<device>`);
/// an MLS leaf is a device, so the device id keeps a user's leaves apart.
Future<Uint8List> mlsCreate({
  required String domain,
  required String userId,
  required String deviceId,
}) => RustLib.instance.api.crateApiMlsMlsCreate(
  domain: domain,
  userId: userId,
  deviceId: deviceId,
);

/// Restores the live client from a persisted state blob.
Future<void> mlsLoad({required List<int> state}) =>
    RustLib.instance.api.crateApiMlsMlsLoad(state: state);

Future<bool> mlsIsLoaded() => RustLib.instance.api.crateApiMlsMlsIsLoaded();

/// Drops the client. Logout: the caller must delete the persisted blob and its data key too.
Future<void> mlsUnload() => RustLib.instance.api.crateApiMlsMlsUnload();

/// This client's credential identity, `userId:deviceId`.
///
/// The authoritative answer to "which device am I?". A restored backup carries the identity of the
/// device it was taken FROM, and the groups inside it hold leaves under that name — so the device
/// it is restored onto has to answer to it, whatever its own storage says.
Future<String> mlsIdentity() => RustLib.instance.api.crateApiMlsMlsIdentity();

/// This client's long-term signature public key.
Future<Uint8List> mlsIdentityKey() =>
    RustLib.instance.api.crateApiMlsMlsIdentityKey();

/// A single-use public KeyPackage to publish.
Future<Bytes> mlsKeyPackage() =>
    RustLib.instance.api.crateApiMlsMlsKeyPackage();

/// A reusable last-resort KeyPackage, so a user can still be added to a group after their
/// single-use stock has been claimed.
Future<Bytes> mlsLastResortKeyPackage() =>
    RustLib.instance.api.crateApiMlsMlsLastResortKeyPackage();

Future<Applied> mlsCreateGroup({required List<int> groupId}) =>
    RustLib.instance.api.crateApiMlsMlsCreateGroup(groupId: groupId);

/// Discards a group so it can be rebuilt — repairing a device that could never join.
Future<Applied> mlsDeleteGroup({required List<int> groupId}) =>
    RustLib.instance.api.crateApiMlsMlsDeleteGroup(groupId: groupId);

/// Whether this client already holds the group. A pure read.
Future<bool> mlsHasGroup({required List<int> groupId}) =>
    RustLib.instance.api.crateApiMlsMlsHasGroup(groupId: groupId);

Future<Applied> mlsJoinFromWelcome({required List<int> welcome}) =>
    RustLib.instance.api.crateApiMlsMlsJoinFromWelcome(welcome: welcome);

/// Exports the GroupInfo a NON-MEMBER needs to join by external commit. A pure read: GroupInfo is a
/// signed snapshot of the current epoch, and producing it changes nothing.
Future<Uint8List> mlsExportGroupInfo({required List<int> groupId}) =>
    RustLib.instance.api.crateApiMlsMlsExportGroupInfo(groupId: groupId);

/// Joins an existing group by EXTERNAL COMMIT — adds this device's own leaf from a member's exported
/// GroupInfo, with no Welcome and no member's help. Returns the external commit to offer the server.
///
/// The group is created here with that commit PENDING. On acceptance call `mlsCommitAccepted` to merge
/// it; on refusal call `mlsDeleteGroup` (NOT `mlsCommitRejected` — an external commit cannot be
/// cleared) and rejoin from fresh GroupInfo.
Future<Bytes> mlsJoinByExternalCommit({required List<int> groupInfo}) => RustLib
    .instance
    .api
    .crateApiMlsMlsJoinByExternalCommit(groupInfo: groupInfo);

Future<Applied> mlsApplyCommit({
  required List<int> groupId,
  required List<int> commit,
}) => RustLib.instance.api.crateApiMlsMlsApplyCommit(
  groupId: groupId,
  commit: commit,
);

/// STAGES the addition of several devices in one Commit, so every newcomer lands at the same epoch.
/// One Welcome covers all of them.
///
/// The Commit is NOT applied. Post it, then call `mlsCommitAccepted` once the server has taken it as
/// the group's next epoch, or `mlsCommitRejected` if another member's Commit landed first. Applying
/// a Commit the server refused forks this device off the group permanently, and silently.
Future<Staged> mlsStageAdd({
  required List<int> groupId,
  required List<Uint8List> keyPackages,
}) => RustLib.instance.api.crateApiMlsMlsStageAdd(
  groupId: groupId,
  keyPackages: keyPackages,
);

/// STAGES the removal of every device belonging to each of `user_ids`.
///
/// Removing one leaf would leave the removed member reading the group from their other phone.
Future<Bytes> mlsStageRemoveUsers({
  required List<int> groupId,
  required List<String> userIds,
}) => RustLib.instance.api.crateApiMlsMlsStageRemoveUsers(
  groupId: groupId,
  userIds: userIds,
);

/// STAGES the removal of the exact leaves named by `identities` (`userId:deviceId`).
///
/// For pruning a ghost device — one whose key material no longer exists anywhere — without taking
/// that person's working phone out along with it.
Future<Bytes> mlsStageRemoveDevices({
  required List<int> groupId,
  required List<String> identities,
}) => RustLib.instance.api.crateApiMlsMlsStageRemoveDevices(
  groupId: groupId,
  identities: identities,
);

/// Merges the Commit we staged, now that the server has accepted it.
Future<Applied> mlsCommitAccepted({required List<int> groupId}) =>
    RustLib.instance.api.crateApiMlsMlsCommitAccepted(groupId: groupId);

/// Discards a Commit the server refused, leaving the group untouched so we can catch up on the
/// winning Commit and try again.
Future<Applied> mlsCommitRejected({required List<int> groupId}) =>
    RustLib.instance.api.crateApiMlsMlsCommitRejected(groupId: groupId);

/// The group's current epoch — what a Commit is proposed against. A pure read.
Future<BigInt> mlsEpoch({required List<int> groupId}) =>
    RustLib.instance.api.crateApiMlsMlsEpoch(groupId: groupId);

/// Every leaf's `userId:deviceId`, so the caller can spot member devices missing from the group and
/// add exactly those. A pure read.
Future<List<String>> mlsMemberIdentities({required List<int> groupId}) =>
    RustLib.instance.api.crateApiMlsMlsMemberIdentities(groupId: groupId);

/// Encrypts an application message.
///
/// MLS destroys the message key as it goes, so the sender can never decrypt this again. The caller
/// must cache the plaintext locally or the message it just sent will render blank forever.
Future<Bytes> mlsEncrypt({
  required List<int> groupId,
  required List<int> plaintext,
}) => RustLib.instance.api.crateApiMlsMlsEncrypt(
  groupId: groupId,
  plaintext: plaintext,
);

/// Decrypts an application message. Consumes the key: a message decrypts exactly once, so the
/// plaintext must be cached on first sight.
///
/// `plaintext == None` means this was a control message, not a failure.
Future<Opened> mlsDecrypt({
  required List<int> groupId,
  required List<int> ciphertext,
}) => RustLib.instance.api.crateApiMlsMlsDecrypt(
  groupId: groupId,
  ciphertext: ciphertext,
);

Future<MlsPreviewOutcome> mlsDecryptPreview({
  required List<int> state,
  required List<Uint8List> groupIds,
  required List<int> ciphertext,
}) => RustLib.instance.api.crateApiMlsMlsDecryptPreview(
  state: state,
  groupIds: groupIds,
  ciphertext: ciphertext,
);

/// Derives a secret from the group for a purpose outside MLS's own messaging — Pheme keys voice-call
/// signalling with it, so the server cannot read the SDP and therefore cannot swap the DTLS
/// fingerprint inside it and sit in the middle of the call.
///
/// A pure read: it churns neither the ratchet nor the key store. It exports from the CURRENT EPOCH
/// only, which is why a caller must catch up before deriving and a receiver that is ahead of the
/// sender cannot derive the sender's key at all.
Future<Uint8List> mlsExportSecret({
  required List<int> groupId,
  required String label,
  required List<int> context,
  required BigInt length,
}) => RustLib.instance.api.crateApiMlsMlsExportSecret(
  groupId: groupId,
  label: label,
  context: context,
  length: length,
);

/// The digits two people read to each other, out of band, to prove the server did not substitute a
/// key and put itself in the middle. Derived from the group's own ratchet tree, never from anything
/// the server says.
Future<String> mlsSafetyNumber({required List<int> groupId}) =>
    RustLib.instance.api.crateApiMlsMlsSafetyNumber(groupId: groupId);

/// Seals the live client's state under a recovery passphrase.
Future<BackupBlob> mlsBackupEncrypt({
  required List<int> passphrase,
  required List<int> plaintext,
}) => RustLib.instance.api.crateApiMlsMlsBackupEncrypt(
  passphrase: passphrase,
  plaintext: plaintext,
);

/// Recovers client state from a sealed backup. Errors on a wrong passphrase.
Future<Uint8List> mlsBackupDecrypt({
  required List<int> passphrase,
  required List<int> salt,
  required List<int> nonce,
  required List<int> ciphertext,
}) => RustLib.instance.api.crateApiMlsMlsBackupDecrypt(
  passphrase: passphrase,
  salt: salt,
  nonce: nonce,
  ciphertext: ciphertext,
);

/// A mutation with no other result.
class Applied {
  final Uint8List state;

  const Applied({required this.state});

  @override
  int get hashCode => state.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Applied &&
          runtimeType == other.runtimeType &&
          state == other.state;
}

/// A sealed key backup, stored server-side. The server sees these three fields and never the
/// passphrase or the plaintext.
class BackupBlob {
  final Uint8List salt;
  final Uint8List nonce;
  final Uint8List ciphertext;

  const BackupBlob({
    required this.salt,
    required this.nonce,
    required this.ciphertext,
  });

  @override
  int get hashCode => salt.hashCode ^ nonce.hashCode ^ ciphertext.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BackupBlob &&
          runtimeType == other.runtimeType &&
          salt == other.salt &&
          nonce == other.nonce &&
          ciphertext == other.ciphertext;
}

/// A mutation whose result is one blob: a key package, or a commit, or a ciphertext.
class Bytes {
  final Uint8List bytes;
  final Uint8List state;

  const Bytes({required this.bytes, required this.state});

  @override
  int get hashCode => bytes.hashCode ^ state.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Bytes &&
          runtimeType == other.runtimeType &&
          bytes == other.bytes &&
          state == other.state;
}

/// Decrypts one message for a NOTIFICATION PREVIEW, and touches nothing else.
///
/// This is the one MLS call that does not go through `CLIENT`, and that is the entire point.
///
/// A preview runs where the app is not: an Android background isolate, an iOS
/// NotificationServiceExtension. Both are contexts the single-client rule was written to keep away
/// from the key store — a background isolate that called `mls_load` would swap the client out from
/// under the foreground one, and a second process would race it to disk. Either way the older state
/// can land last: a ratchet saved as though it had not moved, which is every message after that
/// point permanently unreadable.
///
/// So this borrows nothing. It takes the state blob by value, builds a throwaway
/// `PreviewClient` from it, reads one message, and drops the lot. `PreviewClient` has no
/// `export_state`, so there is nowhere for the advanced ratchet to go and no way for a later edit
/// to persist it by accident. The real client — in whichever isolate or process owns it — is
/// untouched and still holds an unconsumed key for that message, and decrypts it again for real
/// when the app opens.
///
/// Note what is NOT returned: a state blob. Every other mutating call here hands one back to
/// persist. This one deliberately cannot, and the asymmetry in the signature is the API telling
/// the caller what it is.
///
/// `None` means there was nothing to preview — control traffic, or a message this device cannot
/// read. Both are ordinary outcomes on this path, not errors.
/// What came of a preview attempt.
///
/// A bare `Option` said only "no preview", which is true of three different situations that want
/// three different responses: a device that does not hold the group at all (the conversation was
/// re-established and this device never joined the new one), a device that holds it but cannot read
/// the message (the on-disk state lags the epoch the message was sent in, or the app already
/// consumed the key), and control traffic that was never meant to be shown.
///
/// Telling them apart from a log line is the whole point — the last two failures in this feature
/// each cost hours precisely because a null did not say which null it was.
class MlsPreviewOutcome {
  /// The message text, when it could be read.
  final Uint8List? plaintext;

  /// How many of the offered groups this device actually holds.
  final int groupsHeld;

  /// How many were offered.
  final int groupsOffered;

  const MlsPreviewOutcome({
    this.plaintext,
    required this.groupsHeld,
    required this.groupsOffered,
  });

  @override
  int get hashCode =>
      plaintext.hashCode ^ groupsHeld.hashCode ^ groupsOffered.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MlsPreviewOutcome &&
          runtimeType == other.runtimeType &&
          plaintext == other.plaintext &&
          groupsHeld == other.groupsHeld &&
          groupsOffered == other.groupsOffered;
}

/// A decrypted message. `plaintext` is `None` for a control message — which is a success, not a
/// failure, and must not be treated as one.
class Opened {
  final Uint8List? plaintext;
  final Uint8List state;

  const Opened({this.plaintext, required this.state});

  @override
  int get hashCode => plaintext.hashCode ^ state.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Opened &&
          runtimeType == other.runtimeType &&
          plaintext == other.plaintext &&
          state == other.state;
}

/// A staged Add: one Welcome covering every newcomer, and the Commit that adds them.
///
/// NOT applied. The server arbitrates: `mlsCommitAccepted` on 200, `mlsCommitRejected` on 409.
class Staged {
  final Uint8List welcome;
  final Uint8List commit;
  final Uint8List state;

  const Staged({
    required this.welcome,
    required this.commit,
    required this.state,
  });

  @override
  int get hashCode => welcome.hashCode ^ commit.hashCode ^ state.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Staged &&
          runtimeType == other.runtimeType &&
          welcome == other.welcome &&
          commit == other.commit &&
          state == other.state;
}
