// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `cipher`

/// Cryptographically random bytes — the data key, and nothing else here needs them.
Future<Uint8List> randomBytes({required BigInt length}) =>
    RustLib.instance.api.crateApiVaultRandomBytes(length: length);

/// Seals the state blob. The nonce is 12 random bytes and is prepended to the ciphertext, so the
/// caller stores one opaque blob and never has to keep the two in step.
Future<Uint8List> vaultSeal({
  required List<int> key,
  required List<int> plaintext,
}) =>
    RustLib.instance.api.crateApiVaultVaultSeal(key: key, plaintext: plaintext);

/// Opens a sealed state blob. Fails on a wrong key or a truncated file, which is what a corrupted
/// or half-written state looks like — and the caller must treat that as "no local keys", not as a
/// crash.
Future<Uint8List> vaultOpen({
  required List<int> key,
  required List<int> sealed,
}) => RustLib.instance.api.crateApiVaultVaultOpen(key: key, sealed: sealed);
