#!/usr/bin/env bash
# One-time bootstrap for local development.
#
#   ./scripts/setup.sh
#
# - Checks prerequisites (go, node, docker).
# - Picks infra host ports, avoiding ones already in use on this machine.
# - Generates a Web Push VAPID key pair.
# - Writes .env.dev (service config) and deploy/.env (docker compose), both
#   gitignored. Re-running keeps your existing values unless you pass --force.

source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

FORCE=0
[ "${1:-}" = "--force" ] && FORCE=1

if [ -f "$ENV_DEV" ] && [ "$FORCE" -eq 0 ]; then
  ok "$ENV_DEV already exists (use --force to regenerate)"
  exit 0
fi

info "Checking prerequisites"
need go
need node
need npm
need docker
need lsof
ok "go $(go version | awk '{print $3}'), node $(node -v), docker present"

info "Selecting infra host ports"
MONGO_HOST_PORT="$(pick_port 27017 37017)"
RABBIT_HOST_PORT="$(pick_port 5672 35672)"
RABBIT_MGMT_HOST_PORT="$(pick_port 15672 45672)"
REDIS_HOST_PORT="$(pick_port 6379 36379)"
for p in \
  "MongoDB:$MONGO_HOST_PORT:27017" \
  "RabbitMQ:$RABBIT_HOST_PORT:5672" \
  "Rabbit UI:$RABBIT_MGMT_HOST_PORT:15672" \
  "Redis:$REDIS_HOST_PORT:6379"; do
  name="${p%%:*}"; rest="${p#*:}"; host="${rest%%:*}"; std="${rest##*:}"
  if [ "$host" != "$std" ]; then
    warn "$name: port $std in use → using $host"
  else
    ok "$name: port $host"
  fi
done

info "Generating VAPID keys"
vapid="$(cd "$REPO_ROOT/api" && go run ./cmd/vapidgen -env)"
VAPID_PUBLIC="$(echo "$vapid" | sed -n 's/^PHEME_VAPID_PUBLIC=//p')"
VAPID_PRIVATE="$(echo "$vapid" | sed -n 's/^PHEME_VAPID_PRIVATE=//p')"
[ -n "$VAPID_PUBLIC" ] && [ -n "$VAPID_PRIVATE" ] || die "VAPID generation failed"
ok "VAPID key pair generated"

JWT_SECRET="dev-$(openssl rand -hex 16 2>/dev/null || echo "change-me-$(date +%s)")"
APP_PORT="${APP_PORT:-8080}"
INGEST_PORT="${INGEST_PORT:-8081}"
WEB_PORT="${WEB_PORT:-5173}"

info "Writing docker compose env → deploy/.env"
cat > "$COMPOSE_ENV" <<EOF
# Generated by scripts/setup.sh — docker compose infrastructure config.
MONGO_USER=pheme
MONGO_PASS=pheme
MONGO_DB=pheme
RABBIT_USER=guest
RABBIT_PASS=guest
MONGO_HOST_PORT=$MONGO_HOST_PORT
RABBIT_HOST_PORT=$RABBIT_HOST_PORT
RABBIT_MGMT_HOST_PORT=$RABBIT_MGMT_HOST_PORT
REDIS_HOST_PORT=$REDIS_HOST_PORT
EOF

info "Writing service env → .env.dev"
cat > "$ENV_DEV" <<EOF
# Generated by scripts/setup.sh — local development service config.
# Sourced by scripts/dev.sh. Safe to edit; re-run setup --force to regenerate.

# Infra host ports (kept in sync with deploy/.env for docker compose).
MONGO_HOST_PORT=$MONGO_HOST_PORT
RABBIT_HOST_PORT=$RABBIT_HOST_PORT
RABBIT_MGMT_HOST_PORT=$RABBIT_MGMT_HOST_PORT
REDIS_HOST_PORT=$REDIS_HOST_PORT

# Backend drivers (use the real infra started by docker compose).
PHEME_STORE_DRIVER=mongo
PHEME_BROKER_DRIVER=rabbit
PHEME_LIVE_DRIVER=redis
PHEME_RATELIMIT_DRIVER=redis
PHEME_PUSH_DRIVER=webpush

# Connection strings (note authSource=admin for the compose root user).
PHEME_MONGO_URI="mongodb://pheme:pheme@127.0.0.1:$MONGO_HOST_PORT/?authSource=admin"
PHEME_MONGO_DB=pheme
PHEME_RABBIT_URI="amqp://guest:guest@127.0.0.1:$RABBIT_HOST_PORT/"
PHEME_REDIS_ADDR="127.0.0.1:$REDIS_HOST_PORT"

# Auth.
PHEME_JWT_SECRET="$JWT_SECRET"
# Comma-separated emails granted the admin role on register/login.
PHEME_ADMIN_EMAILS=""
# Registration is invite-only by default; set to false for an open dev instance.
PHEME_INVITE_ONLY=false

# Web Push.
PHEME_VAPID_PUBLIC="$VAPID_PUBLIC"
PHEME_VAPID_PRIVATE="$VAPID_PRIVATE"
PHEME_VAPID_SUBJECT="mailto:admin@example.com"

# Service listen addresses.
PHEME_APP_ADDR=":$APP_PORT"
PHEME_INGEST_ADDR=":$INGEST_PORT"

# Web dev server.
WEB_PORT=$WEB_PORT
EOF

info "Writing web env → web/.env.local"
cat > "$REPO_ROOT/web/.env.local" <<EOF
# Generated by scripts/setup.sh.
VITE_API_BASE=http://localhost:$APP_PORT
EOF

echo
ok "Setup complete."
echo "  Next:  ${C_BOLD}./scripts/dev.sh${C_RESET}   (or: make dev)"
echo "  Admin: set PHEME_ADMIN_EMAILS in .env.dev to grant yourself admin."
