// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/mls.dart';
import 'api/vault.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiMlsInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -172677608;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_pheme_mobile',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiMlsInitApp();

  Future<Applied> crateApiMlsMlsApplyCommit({
    required List<int> groupId,
    required List<int> commit,
  });

  Future<Uint8List> crateApiMlsMlsBackupDecrypt({
    required List<int> passphrase,
    required List<int> salt,
    required List<int> nonce,
    required List<int> ciphertext,
  });

  Future<BackupBlob> crateApiMlsMlsBackupEncrypt({
    required List<int> passphrase,
    required List<int> plaintext,
  });

  Future<Applied> crateApiMlsMlsCommitAccepted({required List<int> groupId});

  Future<Applied> crateApiMlsMlsCommitRejected({required List<int> groupId});

  Future<Uint8List> crateApiMlsMlsCreate({
    required String userId,
    required String deviceId,
  });

  Future<Applied> crateApiMlsMlsCreateGroup({required List<int> groupId});

  Future<Opened> crateApiMlsMlsDecrypt({
    required List<int> groupId,
    required List<int> ciphertext,
  });

  Future<Applied> crateApiMlsMlsDeleteGroup({required List<int> groupId});

  Future<Bytes> crateApiMlsMlsEncrypt({
    required List<int> groupId,
    required List<int> plaintext,
  });

  Future<BigInt> crateApiMlsMlsEpoch({required List<int> groupId});

  Future<Uint8List> crateApiMlsMlsExportSecret({
    required List<int> groupId,
    required String label,
    required List<int> context,
    required BigInt length,
  });

  Future<bool> crateApiMlsMlsHasGroup({required List<int> groupId});

  Future<String> crateApiMlsMlsIdentity();

  Future<Uint8List> crateApiMlsMlsIdentityKey();

  Future<bool> crateApiMlsMlsIsLoaded();

  Future<Applied> crateApiMlsMlsJoinFromWelcome({required List<int> welcome});

  Future<Bytes> crateApiMlsMlsKeyPackage();

  Future<Bytes> crateApiMlsMlsLastResortKeyPackage();

  Future<void> crateApiMlsMlsLoad({required List<int> state});

  Future<List<String>> crateApiMlsMlsMemberIdentities({
    required List<int> groupId,
  });

  Future<String> crateApiMlsMlsSafetyNumber({required List<int> groupId});

  Future<Staged> crateApiMlsMlsStageAdd({
    required List<int> groupId,
    required List<Uint8List> keyPackages,
  });

  Future<Bytes> crateApiMlsMlsStageRemoveDevices({
    required List<int> groupId,
    required List<String> identities,
  });

  Future<Bytes> crateApiMlsMlsStageRemoveUsers({
    required List<int> groupId,
    required List<String> userIds,
  });

  Future<void> crateApiMlsMlsUnload();

  Future<Uint8List> crateApiVaultRandomBytes({required BigInt length});

  Future<Uint8List> crateApiVaultVaultOpen({
    required List<int> key,
    required List<int> sealed,
  });

  Future<Uint8List> crateApiVaultVaultSeal({
    required List<int> key,
    required List<int> plaintext,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiMlsInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMlsInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMlsInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<Applied> crateApiMlsMlsApplyCommit({
    required List<int> groupId,
    required List<int> commit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(groupId, serializer);
          sse_encode_list_prim_u_8_loose(commit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_applied,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMlsMlsApplyCommitConstMeta,
        argValues: [groupId, commit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMlsMlsApplyCommitConstMeta => const TaskConstMeta(
    debugName: "mls_apply_commit",
    argNames: ["groupId", "commit"],
  );

  @override
  Future<Uint8List> crateApiMlsMlsBackupDecrypt({
    required List<int> passphrase,
    required List<int> salt,
    required List<int> nonce,
    required List<int> ciphertext,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(passphrase, serializer);
          sse_encode_list_prim_u_8_loose(salt, serializer);
          sse_encode_list_prim_u_8_loose(nonce, serializer);
          sse_encode_list_prim_u_8_loose(ciphertext, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMlsMlsBackupDecryptConstMeta,
        argValues: [passphrase, salt, nonce, ciphertext],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMlsMlsBackupDecryptConstMeta =>
      const TaskConstMeta(
        debugName: "mls_backup_decrypt",
        argNames: ["passphrase", "salt", "nonce", "ciphertext"],
      );

  @override
  Future<BackupBlob> crateApiMlsMlsBackupEncrypt({
    required List<int> passphrase,
    required List<int> plaintext,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(passphrase, serializer);
          sse_encode_list_prim_u_8_loose(plaintext, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_backup_blob,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMlsMlsBackupEncryptConstMeta,
        argValues: [passphrase, plaintext],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMlsMlsBackupEncryptConstMeta =>
      const TaskConstMeta(
        debugName: "mls_backup_encrypt",
        argNames: ["passphrase", "plaintext"],
      );

  @override
  Future<Applied> crateApiMlsMlsCommitAccepted({required List<int> groupId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(groupId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_applied,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMlsMlsCommitAcceptedConstMeta,
        argValues: [groupId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMlsMlsCommitAcceptedConstMeta =>
      const TaskConstMeta(
        debugName: "mls_commit_accepted",
        argNames: ["groupId"],
      );

  @override
  Future<Applied> crateApiMlsMlsCommitRejected({required List<int> groupId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(groupId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_applied,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMlsMlsCommitRejectedConstMeta,
        argValues: [groupId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMlsMlsCommitRejectedConstMeta =>
      const TaskConstMeta(
        debugName: "mls_commit_rejected",
        argNames: ["groupId"],
      );

  @override
  Future<Uint8List> crateApiMlsMlsCreate({
    required String userId,
    required String deviceId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(userId, serializer);
          sse_encode_String(deviceId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMlsMlsCreateConstMeta,
        argValues: [userId, deviceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMlsMlsCreateConstMeta => const TaskConstMeta(
    debugName: "mls_create",
    argNames: ["userId", "deviceId"],
  );

  @override
  Future<Applied> crateApiMlsMlsCreateGroup({required List<int> groupId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(groupId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_applied,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMlsMlsCreateGroupConstMeta,
        argValues: [groupId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMlsMlsCreateGroupConstMeta =>
      const TaskConstMeta(debugName: "mls_create_group", argNames: ["groupId"]);

  @override
  Future<Opened> crateApiMlsMlsDecrypt({
    required List<int> groupId,
    required List<int> ciphertext,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(groupId, serializer);
          sse_encode_list_prim_u_8_loose(ciphertext, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opened,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMlsMlsDecryptConstMeta,
        argValues: [groupId, ciphertext],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMlsMlsDecryptConstMeta => const TaskConstMeta(
    debugName: "mls_decrypt",
    argNames: ["groupId", "ciphertext"],
  );

  @override
  Future<Applied> crateApiMlsMlsDeleteGroup({required List<int> groupId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(groupId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_applied,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMlsMlsDeleteGroupConstMeta,
        argValues: [groupId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMlsMlsDeleteGroupConstMeta =>
      const TaskConstMeta(debugName: "mls_delete_group", argNames: ["groupId"]);

  @override
  Future<Bytes> crateApiMlsMlsEncrypt({
    required List<int> groupId,
    required List<int> plaintext,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(groupId, serializer);
          sse_encode_list_prim_u_8_loose(plaintext, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bytes,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMlsMlsEncryptConstMeta,
        argValues: [groupId, plaintext],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMlsMlsEncryptConstMeta => const TaskConstMeta(
    debugName: "mls_encrypt",
    argNames: ["groupId", "plaintext"],
  );

  @override
  Future<BigInt> crateApiMlsMlsEpoch({required List<int> groupId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(groupId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMlsMlsEpochConstMeta,
        argValues: [groupId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMlsMlsEpochConstMeta =>
      const TaskConstMeta(debugName: "mls_epoch", argNames: ["groupId"]);

  @override
  Future<Uint8List> crateApiMlsMlsExportSecret({
    required List<int> groupId,
    required String label,
    required List<int> context,
    required BigInt length,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(groupId, serializer);
          sse_encode_String(label, serializer);
          sse_encode_list_prim_u_8_loose(context, serializer);
          sse_encode_usize(length, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMlsMlsExportSecretConstMeta,
        argValues: [groupId, label, context, length],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMlsMlsExportSecretConstMeta => const TaskConstMeta(
    debugName: "mls_export_secret",
    argNames: ["groupId", "label", "context", "length"],
  );

  @override
  Future<bool> crateApiMlsMlsHasGroup({required List<int> groupId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(groupId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMlsMlsHasGroupConstMeta,
        argValues: [groupId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMlsMlsHasGroupConstMeta =>
      const TaskConstMeta(debugName: "mls_has_group", argNames: ["groupId"]);

  @override
  Future<String> crateApiMlsMlsIdentity() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMlsMlsIdentityConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMlsMlsIdentityConstMeta =>
      const TaskConstMeta(debugName: "mls_identity", argNames: []);

  @override
  Future<Uint8List> crateApiMlsMlsIdentityKey() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMlsMlsIdentityKeyConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMlsMlsIdentityKeyConstMeta =>
      const TaskConstMeta(debugName: "mls_identity_key", argNames: []);

  @override
  Future<bool> crateApiMlsMlsIsLoaded() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMlsMlsIsLoadedConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMlsMlsIsLoadedConstMeta =>
      const TaskConstMeta(debugName: "mls_is_loaded", argNames: []);

  @override
  Future<Applied> crateApiMlsMlsJoinFromWelcome({required List<int> welcome}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(welcome, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_applied,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMlsMlsJoinFromWelcomeConstMeta,
        argValues: [welcome],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMlsMlsJoinFromWelcomeConstMeta =>
      const TaskConstMeta(
        debugName: "mls_join_from_welcome",
        argNames: ["welcome"],
      );

  @override
  Future<Bytes> crateApiMlsMlsKeyPackage() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bytes,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMlsMlsKeyPackageConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMlsMlsKeyPackageConstMeta =>
      const TaskConstMeta(debugName: "mls_key_package", argNames: []);

  @override
  Future<Bytes> crateApiMlsMlsLastResortKeyPackage() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bytes,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMlsMlsLastResortKeyPackageConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMlsMlsLastResortKeyPackageConstMeta =>
      const TaskConstMeta(
        debugName: "mls_last_resort_key_package",
        argNames: [],
      );

  @override
  Future<void> crateApiMlsMlsLoad({required List<int> state}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(state, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMlsMlsLoadConstMeta,
        argValues: [state],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMlsMlsLoadConstMeta =>
      const TaskConstMeta(debugName: "mls_load", argNames: ["state"]);

  @override
  Future<List<String>> crateApiMlsMlsMemberIdentities({
    required List<int> groupId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(groupId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMlsMlsMemberIdentitiesConstMeta,
        argValues: [groupId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMlsMlsMemberIdentitiesConstMeta =>
      const TaskConstMeta(
        debugName: "mls_member_identities",
        argNames: ["groupId"],
      );

  @override
  Future<String> crateApiMlsMlsSafetyNumber({required List<int> groupId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(groupId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMlsMlsSafetyNumberConstMeta,
        argValues: [groupId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMlsMlsSafetyNumberConstMeta => const TaskConstMeta(
    debugName: "mls_safety_number",
    argNames: ["groupId"],
  );

  @override
  Future<Staged> crateApiMlsMlsStageAdd({
    required List<int> groupId,
    required List<Uint8List> keyPackages,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(groupId, serializer);
          sse_encode_list_list_prim_u_8_strict(keyPackages, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_staged,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMlsMlsStageAddConstMeta,
        argValues: [groupId, keyPackages],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMlsMlsStageAddConstMeta => const TaskConstMeta(
    debugName: "mls_stage_add",
    argNames: ["groupId", "keyPackages"],
  );

  @override
  Future<Bytes> crateApiMlsMlsStageRemoveDevices({
    required List<int> groupId,
    required List<String> identities,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(groupId, serializer);
          sse_encode_list_String(identities, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bytes,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMlsMlsStageRemoveDevicesConstMeta,
        argValues: [groupId, identities],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMlsMlsStageRemoveDevicesConstMeta =>
      const TaskConstMeta(
        debugName: "mls_stage_remove_devices",
        argNames: ["groupId", "identities"],
      );

  @override
  Future<Bytes> crateApiMlsMlsStageRemoveUsers({
    required List<int> groupId,
    required List<String> userIds,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(groupId, serializer);
          sse_encode_list_String(userIds, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bytes,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMlsMlsStageRemoveUsersConstMeta,
        argValues: [groupId, userIds],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMlsMlsStageRemoveUsersConstMeta =>
      const TaskConstMeta(
        debugName: "mls_stage_remove_users",
        argNames: ["groupId", "userIds"],
      );

  @override
  Future<void> crateApiMlsMlsUnload() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMlsMlsUnloadConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMlsMlsUnloadConstMeta =>
      const TaskConstMeta(debugName: "mls_unload", argNames: []);

  @override
  Future<Uint8List> crateApiVaultRandomBytes({required BigInt length}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_usize(length, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiVaultRandomBytesConstMeta,
        argValues: [length],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultRandomBytesConstMeta =>
      const TaskConstMeta(debugName: "random_bytes", argNames: ["length"]);

  @override
  Future<Uint8List> crateApiVaultVaultOpen({
    required List<int> key,
    required List<int> sealed,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(key, serializer);
          sse_encode_list_prim_u_8_loose(sealed, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiVaultVaultOpenConstMeta,
        argValues: [key, sealed],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultVaultOpenConstMeta =>
      const TaskConstMeta(debugName: "vault_open", argNames: ["key", "sealed"]);

  @override
  Future<Uint8List> crateApiVaultVaultSeal({
    required List<int> key,
    required List<int> plaintext,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(key, serializer);
          sse_encode_list_prim_u_8_loose(plaintext, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiVaultVaultSealConstMeta,
        argValues: [key, plaintext],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultVaultSealConstMeta => const TaskConstMeta(
    debugName: "vault_seal",
    argNames: ["key", "plaintext"],
  );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  Applied dco_decode_applied(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return Applied(state: dco_decode_list_prim_u_8_strict(arr[0]));
  }

  @protected
  BackupBlob dco_decode_backup_blob(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return BackupBlob(
      salt: dco_decode_list_prim_u_8_strict(arr[0]),
      nonce: dco_decode_list_prim_u_8_strict(arr[1]),
      ciphertext: dco_decode_list_prim_u_8_strict(arr[2]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  Bytes dco_decode_bytes(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return Bytes(
      bytes: dco_decode_list_prim_u_8_strict(arr[0]),
      state: dco_decode_list_prim_u_8_strict(arr[1]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_list_prim_u_8_strict).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  Opened dco_decode_opened(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return Opened(
      plaintext: dco_decode_opt_list_prim_u_8_strict(arr[0]),
      state: dco_decode_list_prim_u_8_strict(arr[1]),
    );
  }

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_prim_u_8_strict(raw);
  }

  @protected
  Staged dco_decode_staged(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return Staged(
      welcome: dco_decode_list_prim_u_8_strict(arr[0]),
      commit: dco_decode_list_prim_u_8_strict(arr[1]),
      state: dco_decode_list_prim_u_8_strict(arr[2]),
    );
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  Applied sse_decode_applied(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_state = sse_decode_list_prim_u_8_strict(deserializer);
    return Applied(state: var_state);
  }

  @protected
  BackupBlob sse_decode_backup_blob(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_salt = sse_decode_list_prim_u_8_strict(deserializer);
    var var_nonce = sse_decode_list_prim_u_8_strict(deserializer);
    var var_ciphertext = sse_decode_list_prim_u_8_strict(deserializer);
    return BackupBlob(
      salt: var_salt,
      nonce: var_nonce,
      ciphertext: var_ciphertext,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  Bytes sse_decode_bytes(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_bytes = sse_decode_list_prim_u_8_strict(deserializer);
    var var_state = sse_decode_list_prim_u_8_strict(deserializer);
    return Bytes(bytes: var_bytes, state: var_state);
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<Uint8List> sse_decode_list_list_prim_u_8_strict(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Uint8List>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_list_prim_u_8_strict(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Opened sse_decode_opened(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_plaintext = sse_decode_opt_list_prim_u_8_strict(deserializer);
    var var_state = sse_decode_list_prim_u_8_strict(deserializer);
    return Opened(plaintext: var_plaintext, state: var_state);
  }

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_prim_u_8_strict(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Staged sse_decode_staged(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_welcome = sse_decode_list_prim_u_8_strict(deserializer);
    var var_commit = sse_decode_list_prim_u_8_strict(deserializer);
    var var_state = sse_decode_list_prim_u_8_strict(deserializer);
    return Staged(welcome: var_welcome, commit: var_commit, state: var_state);
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_applied(Applied self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.state, serializer);
  }

  @protected
  void sse_encode_backup_blob(BackupBlob self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.salt, serializer);
    sse_encode_list_prim_u_8_strict(self.nonce, serializer);
    sse_encode_list_prim_u_8_strict(self.ciphertext, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_bytes(Bytes self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.bytes, serializer);
    sse_encode_list_prim_u_8_strict(self.state, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_list_prim_u_8_strict(
    List<Uint8List> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_list_prim_u_8_strict(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opened(Opened self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_list_prim_u_8_strict(self.plaintext, serializer);
    sse_encode_list_prim_u_8_strict(self.state, serializer);
  }

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_prim_u_8_strict(self, serializer);
    }
  }

  @protected
  void sse_encode_staged(Staged self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.welcome, serializer);
    sse_encode_list_prim_u_8_strict(self.commit, serializer);
    sse_encode_list_prim_u_8_strict(self.state, serializer);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
